### ISSUE TITLE
[Feature]: 로비 페이지 개발

### ISSUE THREAD

**Issue by usageness** [InHyeok-J/relay-mind-web#14]
## 기능 설명
- 프로젝트 로비 페이지 view 개발
- 새로고침 시 사용자 로그인 유지 기능

## Tasks
- [x] 로비 페이지 UI 디자인
- [x] 인 게임 UI 디자인
- [x] 사용자 로그인 유지 기능
- [x] 로비 페이지 view 개발
- [x] 게임시작 전 view 개발
