### ISSUE TITLE
[Feature]:프론트 소켓 셋팅 및 방 입장

### ISSUE THREAD

**Issue by InHyeok-J** [InHyeok-J/relay-mind-web#24]
## 기능 설명
- React 에 Socket 셋팅
- 유저정보 필요한 라우터에 로직 추가
- 방 입장 시 password 검사 로직 추가
- 접속 유저 리스트 추가
## Tasks
- [x] React 에 Socket 셋팅
- [x] 유저정보 필요한 라우터에 로직 추가
- [x]  방 입장 시 password 검사 로직 추가
- [x] 접속 유저 리스트
