### ISSUE TITLE
[Feature]: 게임 시작 및 게임 진행

### ISSUE THREAD

**Issue by InHyeok-J** [InHyeok-J/relay-mind-web#32]
## 기능 설명
- 게임 시작 및 게임 진행
- 게임 시작시 레디스에 저장된 유저 정보를 바탕으로 DB에 업데이트 및 게임 시작
- 각 게임별로 상태 저장(Redis) 이후 작업 
## Tasks
- [x] 게임 시작 및 DB 업데이트
- [x] 게임 시작 후-> 키워드 입력 단계 및 키워드 입력
- [x] 키워드 입력 후 참여한 인원 랜덤으로 키워드 섞기
- [ ] 채팅 입력, 자유롭게 입력가능
- [ ] 마지막(전체 다 돌았을때 채팅으로 정답 검사할 수 있는 로직 구현)
