### ISSUE TITLE
[Feature]: README.md 문서 작성

### ISSUE THREAD

**Issue by usageness** [InHyeok-J/relay-mind-web#33]
## 기능 설명
- 레포지토리 메인에 노출될  **README.md** 문서 작성

## Tasks
- [ ] 설치 및 실행 방법 포함
- [ ] 실행 화면 포함
- [ ] 서비스 이용 방법 포함
