### ISSUE TITLE
[Feature]: 메인 페이지 개발

### ISSUE THREAD

**Issue by usageness** [InHyeok-J/relay-mind-web#5]
## 기능 설명
- 프로젝트 메인 페이지 view 개발
- API 통신을 통한 로그인, 회원가입 기능 개발

## Tasks
- [x] 메인 페이지 디자인
- [x] 프로젝트 로고 제작
- [x] 로그인 / 회원가입 모달 제작
- [x] 로그인 API 연결
